const columns = [
  {name: 'ZAWODNIK', uid: 'name', sortable: true},
  {name: 'FORMUŁY', uid: 'formulas'},
  {name: 'DATA URODZENIA  ', uid: 'birthdate', sortable: true},
  {name: 'ZGODA', uid: 'consent', sortable: true},
  {name: 'OPŁATA', uid: 'payment', sortable: true},
  {name: 'WAGA', uid: 'weight', sortable: true},
  {name: 'WZROST', uid: 'height', sortable: true},
  {name: 'BADANIA LEKARSKIE', uid: 'medical_checkups', sortable: true},
  {name: 'STOPIEŃ', uid: 'level', sortable: true},
  {name: 'GRUPY  ', uid: 'groups'},
  {name: '', uid: 'actions'},
];

const groupOptions = [
  {name: 'Kickboxing Dinusie', uid: 'Kickboxing Dinusie', color: '#FFC107'},
  {name: 'Kickboxing Juniorzy', uid: 'Kickboxing Juniorzy', color: '#FF5722'},
  {name: 'Kickboxing Seniorzy', uid: 'Kickboxing Seniorzy', color: '#4CAF50'},
  {name: 'Kickboxing Kadeci', uid: 'Kickboxing Kadeci', color: '#2196F3'},
  {name: 'Yoga', uid: 'Yoga', color: '#9C27B0'},
  {name: 'Pilates', uid: 'Pilates', color: '#E91E63'},
];

const users = [
  {
    id: 1,
    name: 'Tony Reichert',
    birthdate: '2023-10-12',
    medical_checkups: '2025-10-12',
    weight: '65kg',
    height: '180cm',
    consent: true,
    payment: false,
    formulas: '- Senior, Pontfighting, -79kg\n- Senior, Light Contact, -79kg',
    groups: [
      {name: 'Kickboxing Dinusie', uid: 'Kickboxing Dinusie'},
      {name: 'Kickboxing Juniorzy', uid: 'Kickboxing Juniorzy'},
    ],
    level: '4 cup',
    avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026024d',
  },
  {
    id: 2,
    name: 'Sarah Connor',
    birthdate: '1998-03-15',
    medical_checkups: '2024-03-01',
    weight: '55kg',
    height: '165cm',
    consent: true,
    payment: true,
    formulas: '- Senior, Yoga, Advanced',
    groups: [{name: 'Yoga', uid: 'Yoga'}],
    level: '5 cup',
    avatar: 'https://i.pravatar.cc/149',
  },
  {
    id: 3,
    name: 'John Smith',
    birthdate: '2000-06-25',
    medical_checkups: '2025-06-15',
    weight: '70kg',
    height: '175cm',
    consent: false,
    payment: false,
    formulas: '- Junior, Light Contact, -74kg',
    groups: [{name: 'Kickboxing Juniorzy', uid: 'Kickboxing Juniorzy'}],
    level: '3 cup',
    avatar: 'https://i.pravatar.cc/148',
  },
  {
    id: 4,
    name: 'Emily Johnson',
    birthdate: '1995-11-08',
    medical_checkups: '2024-11-20',
    weight: '60kg',
    height: '170cm',
    consent: true,
    payment: true,
    formulas: '- Senior, Pilates, Beginner',
    groups: [{name: 'Pilates', uid: 'Pilates'}],
    level: '1 cup',
    avatar: 'https://i.pravatar.cc/147',
  },
  {
    id: 5,
    name: 'Michael Brown',
    birthdate: '1988-02-14',
    medical_checkups: '2025-02-10',
    weight: '85kg',
    height: '185cm',
    consent: true,
    payment: true,
    formulas: '- Senior, Heavyweight, -90kg',
    groups: [
      {name: 'Kickboxing Seniorzy', uid: 'Kickboxing Seniorzy'},
      {name: 'Kickboxing Kadeci', uid: 'Kickboxing Kadeci'},
    ],
    level: '6 cup',
    avatar: 'https://i.pravatar.cc/146',
  },
  {
    id: 6,
    name: 'Anna Garcia',
    birthdate: '2003-09-30',
    medical_checkups: '2024-09-25',
    weight: '50kg',
    height: '160cm',
    consent: true,
    payment: false,
    formulas: '- Junior, Pointfighting, -55kg',
    groups: [{name: 'Kickboxing Dinusie', uid: 'Kickboxing Dinusie'}],
    level: '2 cup',
    avatar: 'https://i.pravatar.cc/145',
  },
  {
    id: 7,
    name: 'Robert Wilson',
    birthdate: '1990-12-19',
    medical_checkups: '2025-12-10',
    weight: '75kg',
    height: '178cm',
    consent: false,
    payment: true,
    formulas: '- Senior, Full Contact, -80kg',
    groups: [{name: 'Kickboxing Seniorzy', uid: 'Kickboxing Seniorzy'}],
    level: '4 cup',
    avatar: 'https://i.pravatar.cc/144',
  },
  {
    id: 8,
    name: 'Sophia Lee',
    birthdate: '2005-04-17',
    medical_checkups: '2024-04-05',
    weight: '48kg',
    height: '158cm',
    consent: true,
    payment: false,
    formulas: '- Cadet, Light Contact, -50kg',
    groups: [{name: 'Kickboxing Kadeci', uid: 'Kickboxing Kadeci'}],
    level: '1 cup',
    avatar: 'https://i.pravatar.cc/143',
  },
  {
    id: 9,
    name: 'James Taylor',
    birthdate: '1997-08-23',
    medical_checkups: '2024-08-15',
    weight: '68kg',
    height: '172cm',
    consent: true,
    payment: true,
    formulas: '- Senior, Yoga, Intermediate',
    groups: [{name: 'Yoga', uid: 'Yoga'}],
    level: '5 cup',
    avatar: 'https://i.pravatar.cc/142',
  },
  {
    id: 10,
    name: 'Olivia Martinez',
    birthdate: '2001-01-11',
    medical_checkups: '2025-01-05',
    weight: '58kg',
    height: '168cm',
    consent: true,
    payment: false,
    formulas: '- Senior, Light Contact, -60kg',
    groups: [
      {name: 'Kickboxing Juniorzy', uid: 'Kickboxing Juniorzy'},
      {name: 'Pilates', uid: 'Pilates'},
    ],
    level: '3 cup',
    avatar: 'https://i.pravatar.cc/141',
  },
  {
    id: 11,
    name: 'William Harris',
    birthdate: '1993-05-03',
    medical_checkups: '2024-05-20',
    weight: '90kg',
    height: '190cm',
    consent: false,
    payment: true,
    formulas: '- Senior, Heavyweight, -95kg',
    groups: [{name: 'Kickboxing Seniorzy', uid: 'Kickboxing Seniorzy'}],
    level: '7 cup',
    avatar: 'https://i.pravatar.cc/140',
  },
];

export {columns, groupOptions, users};
