const exampleGroupPaymentsData = [
  {
    name: 'Kickboxing Dinusie',
    color: '#97C0FF',
    amountPaid: 2300,
    amountToBePaid: 2700,
    paidCount: 17,
    toBePaidCount: 19,
    payers: [
      {name: 'Jan Kowalski', amount: 140, isPaid: true},
      {name: 'Anna Nowak', amount: 120, isPaid: true},
      {name: 'Marek Kowal', amount: 140, isPaid: false},
      {name: 'Kasia Nowak', amount: 120, isPaid: false},
      {name: 'Szymon Nowacki', amount: 140, isPaid: true},
    ],
  },
  {
    name: 'Taekwondo smyki',
    color: '#FDFF97',
    amountPaid: 2300,
    amountToBePaid: 2700,
    paidCount: 17,
    toBePaidCount: 19,
    payers: [
      {name: 'Jan Kowalski', amount: 140, isPaid: true},
      {name: 'Anna Nowak', amount: 120, isPaid: true},
      {name: 'Marek Kowal', amount: 140, isPaid: false},
      {name: 'Kasia Nowak', amount: 120, isPaid: false},
      {name: 'Szymon Nowacki', amount: 140, isPaid: true},
      {name: 'Kamil Kowal', amount: 120, isPaid: true},
      {name: 'Aneta Zielińska', amount: 140, isPaid: false},
      {name: 'Janusz Kowalski', amount: 120, isPaid: true},
      {name: 'Anna Kowalska', amount: 140, isPaid: true},
    ],
  },
  {
    name: 'Yoga',
    color: '#FFA7D6',
    amountPaid: 2300,
    amountToBePaid: 2700,
    paidCount: 17,
    toBePaidCount: 19,
    payers: [
      {name: 'Jan Kowalski', amount: 140, isPaid: true},
      {name: 'Anna Nowak', amount: 120, isPaid: true},
      {name: 'Marek Kowal', amount: 140, isPaid: false},
      {name: 'Kasia Nowak', amount: 120, isPaid: false},
      {name: 'Szymon Nowacki', amount: 140, isPaid: true},
      {name: 'Kamil Kowal', amount: 120, isPaid: true},
      {name: 'Aneta Zielińska', amount: 140, isPaid: false},
    ],
  },
  {
    name: 'Boks',
    color: '#ff0000',
    amountPaid: 2300,
    amountToBePaid: 2700,
    paidCount: 17,
    toBePaidCount: 19,
    payers: [
      {name: 'Jan Kowalski', amount: 140, isPaid: true},
      {name: 'Anna Nowak', amount: 120, isPaid: true},
      {name: 'Marek Kowal', amount: 140, isPaid: false},
      {name: 'Kasia Nowak', amount: 120, isPaid: false},
      {name: 'Szymon Nowacki', amount: 140, isPaid: true},
      {name: 'Kamil Kowal', amount: 120, isPaid: true},
      {name: 'Aneta Zielińska', amount: 140, isPaid: false},
      {name: 'Jan Kowalski', amount: 140, isPaid: true},
      {name: 'Anna Nowak', amount: 120, isPaid: true},
      {name: 'Marek Kowal', amount: 140, isPaid: false},
      {name: 'Kasia Nowak', amount: 120, isPaid: false},
      {name: 'Szymon Nowacki', amount: 140, isPaid: true},
      {name: 'Kamil Kowal', amount: 120, isPaid: true},
      {name: 'Aneta Zielińska', amount: 140, isPaid: false},
    ],
  },
  {
    name: 'Kickboxing Dinusie',
    color: '#97C0FF',
    amountPaid: 2300,
    amountToBePaid: 2700,
    paidCount: 17,
    toBePaidCount: 19,
    payers: [
      {name: 'Jan Kowalski', amount: 140, isPaid: true},
      {name: 'Anna Nowak', amount: 120, isPaid: true},
      {name: 'Marek Kowal', amount: 140, isPaid: false},
      {name: 'Kasia Nowak', amount: 120, isPaid: false},
      {name: 'Szymon Nowacki', amount: 140, isPaid: true},
    ],
  },
  {
    name: 'Taekwondo smyki',
    color: '#FDFF97',
    amountPaid: 2300,
    amountToBePaid: 2700,
    paidCount: 17,
    toBePaidCount: 19,
    payers: [
      {name: 'Jan Kowalski', amount: 140, isPaid: true},
      {name: 'Anna Nowak', amount: 120, isPaid: true},
      {name: 'Marek Kowal', amount: 140, isPaid: false},
      {name: 'Kasia Nowak', amount: 120, isPaid: false},
      {name: 'Szymon Nowacki', amount: 140, isPaid: true},
      {name: 'Kamil Kowal', amount: 120, isPaid: true},
      {name: 'Aneta Zielińska', amount: 140, isPaid: false},
      {name: 'Janusz Kowalski', amount: 120, isPaid: true},
      {name: 'Anna Kowalska', amount: 140, isPaid: true},
    ],
  },
  {
    name: 'Yoga',
    color: '#FFA7D6',
    amountPaid: 2300,
    amountToBePaid: 2700,
    paidCount: 17,
    toBePaidCount: 19,
    payers: [
      {name: 'Jan Kowalski', amount: 140, isPaid: true},
      {name: 'Anna Nowak', amount: 120, isPaid: true},
      {name: 'Marek Kowal', amount: 140, isPaid: false},
      {name: 'Kasia Nowak', amount: 120, isPaid: false},
      {name: 'Szymon Nowacki', amount: 140, isPaid: true},
      {name: 'Kamil Kowal', amount: 120, isPaid: true},
      {name: 'Aneta Zielińska', amount: 140, isPaid: false},
    ],
  },
  {
    name: 'Boks',
    color: '#ff0000',
    amountPaid: 2300,
    amountToBePaid: 2700,
    paidCount: 17,
    toBePaidCount: 19,
    payers: [
      {name: 'Jan Kowalski', amount: 140, isPaid: true},
      {name: 'Anna Nowak', amount: 120, isPaid: true},
      {name: 'Marek Kowal', amount: 140, isPaid: false},
      {name: 'Kasia Nowak', amount: 120, isPaid: false},
      {name: 'Szymon Nowacki', amount: 140, isPaid: true},
      {name: 'Kamil Kowal', amount: 120, isPaid: true},
      {name: 'Aneta Zielińska', amount: 140, isPaid: false},
      {name: 'Jan Kowalski', amount: 140, isPaid: true},
      {name: 'Anna Nowak', amount: 120, isPaid: true},
      {name: 'Marek Kowal', amount: 140, isPaid: false},
      {name: 'Kasia Nowak', amount: 120, isPaid: false},
      {name: 'Szymon Nowacki', amount: 140, isPaid: true},
      {name: 'Kamil Kowal', amount: 120, isPaid: true},
      {name: 'Aneta Zielińska', amount: 140, isPaid: false},
    ],
  },
];

export default exampleGroupPaymentsData;
