const columns = [
  {name: 'ID', uid: 'id', sortable: true},
  {name: 'ZAMAWIAJĄCY', uid: 'name', sortable: true},
  {name: 'DATA ZAMÓWIENIA', uid: 'date', sortable: true},
  {name: 'ZAMÓWIENIE', uid: 'order'},
  {name: 'AGE', uid: 'age', sortable: true},
  {name: 'ROLE', uid: 'role', sortable: true},
  {name: 'TEAM', uid: 'team'},
  {name: 'EMAIL', uid: 'email'},
  {name: 'STATUS', uid: 'status', sortable: true},
  {name: '', uid: 'actions'},
];

const statusOptions = [
  {name: 'Zrealizowane', uid: 'Zrealizowane'},
  {name: 'Opłacone', uid: 'Opłacone'},
  {name: 'Nieopłacone', uid: 'Nieopłacone'},
];

const users = [
  {
    id: 1,
    name: 'Tony Reichert',
    date: '2023-10-12',
    order: 'Spodnie do kickboxingu, niebieskie, 180cm',
    role: 'CEO',
    team: 'Management',
    status: 'Zrealizowane',
    age: '29',
    avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026024d',
    email: 'tony.reichert@example.com',
  },
  {
    id: 2,
    name: 'Zoey Lang',
    date: '2023-10-11',
    order: 'Spodnie do kickboxingu, czerwone, 160cm',
    role: 'Tech Lead',
    team: 'Development',
    status: 'Opłacone',
    age: '25',
    avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026704d',
    email: 'zoey.lang@example.com',
  },
  {
    id: 3,
    name: 'Jane Fisher',
    date: '2023-10-10',
    order: 'Spodnie do kickboxingu, niebieskie, 180cm',
    role: 'Sr. Dev',
    team: 'Development',
    status: 'Zrealizowane',
    age: '22',
    avatar: 'https://i.pravatar.cc/150?u=a04258114e29026702d',
    email: 'jane.fisher@example.com',
  },
  {
    id: 4,
    name: 'William Howard',
    date: '2023-10-09',
    order: 'Rękawice bokserskie Eva Pro 14oz',
    role: 'C.M.',
    team: 'Marketing',
    status: 'Nieopłacone',
    age: '28',
    avatar: 'https://i.pravatar.cc/150?u=a048581f4e29026701d',
    email: 'william.howard@example.com',
  },
  {
    id: 5,
    name: 'Kristen Copper',
    date: '2023-10-07',
    role: 'S. Manager',
    team: 'Sales',
    status: 'Zrealizowane',
    age: '24',
    avatar: 'https://i.pravatar.cc/150?u=a092581d4ef9026700d',
    email: 'kristen.cooper@example.com',
  },
  {
    id: 6,
    name: 'Brian Kim',
    date: '2023-10-06',
    order: 'Rękawice bokserskie Eva Pro 14oz,\nSzczęka biała',
    role: 'P. Manager',
    team: 'Management',
    age: '29',
    avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026024d',
    email: 'brian.kim@example.com',
    status: 'Zrealizowane',
  },
  {
    id: 7,
    name: 'Michael Hunt',
    date: '2023-10-02',
    role: 'Designer',
    team: 'Design',
    status: 'Opłacone',
    age: '27',
    avatar: 'https://i.pravatar.cc/150?u=a042581f4e29027007d',
    email: 'michael.hunt@example.com',
  },
  {
    id: 8,
    name: 'Samantha Brooks',
    date: '2023-10-01',
    role: 'HR Manager',
    team: 'HR',
    status: 'Zrealizowane',
    age: '31',
    avatar: 'https://i.pravatar.cc/150?u=a042581f4e27027008d',
    email: 'samantha.brooks@example.com',
  },
  {
    id: 9,
    name: 'Frank Harrison',
    date: '2023-10-01',
    role: 'F. Manager',
    team: 'Finance',
    status: 'Nieopłacone',
    age: '33',
    avatar: 'https://i.pravatar.cc/150?img=4',
    email: 'frank.harrison@example.com',
  },
  {
    id: 10,
    name: 'Emma Adams',
    date: '2023-10-01',
    role: 'Ops Manager',
    team: 'Operations',
    status: 'Zrealizowane',
    age: '35',
    avatar: 'https://i.pravatar.cc/150?img=5',
    email: 'emma.adams@example.com',
  },
  {
    id: 11,
    name: 'Brandon Stevens',
    date: '2023-10-01',
    role: 'Jr. Dev',
    team: 'Development',
    status: 'Zrealizowane',
    age: '22',
    avatar: 'https://i.pravatar.cc/150?img=8',
    email: 'brandon.stevens@example.com',
  },
  {
    id: 12,
    name: 'Megan Richards',
    date: '2023-09-26',
    role: 'P. Manager',
    team: 'Product',
    status: 'Opłacone',
    age: '28',
    avatar: 'https://i.pravatar.cc/150?img=10',
    email: 'megan.richards@example.com',
  },
  {
    id: 13,
    name: 'Oliver Scott',
    date: '2023-09-26',
    role: 'S. Manager',
    team: 'Security',
    status: 'Zrealizowane',
    age: '37',
    avatar: 'https://i.pravatar.cc/150?img=12',
    email: 'oliver.scott@example.com',
  },
  {
    id: 14,
    name: 'Grace Allen',
    date: '2023-09-26',
    role: 'M. Specialist',
    team: 'Marketing',
    status: 'Zrealizowane',
    age: '30',
    avatar: 'https://i.pravatar.cc/150?img=16',
    email: 'grace.allen@example.com',
  },
  {
    id: 15,
    name: 'Noah Carter',
    date: '2023-09-26',
    role: 'IT Specialist',
    team: 'I. Technology',
    status: 'Opłacone',
    age: '31',
    avatar: 'https://i.pravatar.cc/150?img=15',
    email: 'noah.carter@example.com',
  },
  {
    id: 16,
    name: 'Ava Perez',
    date: '2023-09-26',
    role: 'Manager',
    team: 'Sales',
    status: 'Zrealizowane',
    age: '29',
    avatar: 'https://i.pravatar.cc/150?img=20',
    email: 'ava.perez@example.com',
  },
  {
    id: 17,
    name: 'Liam Johnson',
    date: '2023-09-26',
    role: 'Data Analyst',
    team: 'Analysis',
    status: 'Zrealizowane',
    age: '28',
    avatar: 'https://i.pravatar.cc/150?img=33',
    email: 'liam.johnson@example.com',
  },
  {
    id: 18,
    name: 'Sophia Taylor',
    date: '2023-09-26',
    role: 'QA Analyst',
    team: 'Testing',
    status: 'Zrealizowane',
    age: '27',
    avatar: 'https://i.pravatar.cc/150?img=29',
    email: 'sophia.taylor@example.com',
  },
  {
    id: 19,
    name: 'Lucas Harris',
    date: '2023-09-26',
    role: 'Administrator',
    team: 'Information Technology',
    status: 'Opłacone',
    age: '32',
    avatar: 'https://i.pravatar.cc/150?img=50',
    email: 'lucas.harris@example.com',
  },
  {
    id: 20,
    name: 'Mia Robinson',
    date: '2023-09-26',
    role: 'Coordinator',
    team: 'Operations',
    status: 'Zrealizowane',
    age: '26',
    avatar: 'https://i.pravatar.cc/150?img=45',
    email: 'mia.robinson@example.com',
  },
];

export {columns, statusOptions, users};
