const columns = [
  {name: 'ZAWODNIK', uid: 'name', sortable: true},
  {name: 'GRUPY  ', uid: 'groups'},
  {name: 'DATA URODZENIA  ', uid: 'birthdate', sortable: true},
  {name: 'NALEŻNOŚĆ', uid: 'amountDue', sortable: true},
  {name: 'SPOSÓB PŁATNOŚCI', uid: 'paymentMethod', sortable: true},
  {name: 'STATUS', uid: 'status', sortable: true},
  {name: '', uid: 'actions'},
];

const statusOptions = [
  {name: 'Opłacone', uid: 'Opłacone'},
  {name: 'Nieopłacone', uid: 'Nieopłacone'},
];

const paymentMethodOptions = [
  {name: 'Gotówka', uid: 'Gotówka'},
  {name: 'Przelew', uid: 'Przelew'},
  {name: 'Karta', uid: 'Karta'},
];

const groupsOptions = [
  {name: 'Kickboxing Dinusie', uid: 'Kickboxing Dinusie', color: '#FFC107'},
  {name: 'Kickboxing Juniorzy', uid: 'Kickboxing Juniorzy', color: '#FF5722'},
  {name: 'Kickboxing Seniorzy', uid: 'Kickboxing Seniorzy', color: '#4CAF50'},
  {name: 'Kickboxing Kadeci', uid: 'Kickboxing Kadeci', color: '#2196F3'},
  {name: 'Yoga', uid: 'Yoga', color: '#9C27B0'},
  {name: 'Pilates', uid: 'Pilates', color: '#E91E63'},
];

const users = [
  {
    id: 1,
    name: 'Tony Reichert',
    amountDue: 140,
    groups: [
      {name: 'Kickboxing Dinusie', uid: 'Kickboxing Dinusie'},
      {name: 'Kickboxing Juniorzy', uid: 'Kickboxing Juniorzy'},
    ],
    birthdate: '2023-10-12',
    medical_checkups: '2025-10-12',
    status: 'Opłacone',
    paymentMethod: 'Gotówka',
    age: '29',
    avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026024d',
    email: 'tony.reichert@example.com',
  },
  {
    id: 2,
    name: 'Zoey Lang',
    amountDue: 140,
    groups: [{name: 'Kickboxing Seniorzy', uid: 'Kickboxing Seniorzy'}],
    birthdate: '2023-10-11',
    medical_checkups: '2023-10-11',
    order: 'Spodnie do kickboxingu, czerwone, 160cm',
    role: 'Tech Lead',
    team: 'Development',
    status: 'Opłacone',
    paymentMethod: 'Przelew',
    age: '25',
    avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026704d',
    email: 'zoey.lang@example.com',
  },
  {
    id: 3,
    name: 'Jane Fisher',
    amountDue: 140,
    groups: [{name: 'Kickboxing Seniorzy', uid: 'Kickboxing Seniorzy'}],
    birthdate: '2023-10-10',
    medical_checkups: '2023-10-10',
    order: 'Spodnie do kickboxingu, niebieskie, 180cm',
    role: 'Sr. Dev',
    team: 'Development',
    status: 'Opłacone',
    paymentMethod: 'Przelew',
    age: '22',
    avatar: 'https://i.pravatar.cc/150?u=a04258114e29026702d',
    email: 'jane.fisher@example.com',
  },
  {
    id: 4,
    name: 'William Howard',
    amountDue: 140,
    groups: [{name: 'Kickboxing Kadeci', uid: 'Kickboxing Kadeci'}],
    birthdate: '2023-10-09',
    medical_checkups: '2023-10-09',
    order: 'Rękawice bokserskie Eva Pro 14oz',
    role: 'C.M.',
    team: 'Marketing',
    status: 'Nieopłacone',
    age: '28',
    avatar: 'https://i.pravatar.cc/150?u=a048581f4e29026701d',
    email: 'william.howard@example.com',
  },
  {
    id: 5,
    name: 'Kristen Copper',
    amountDue: 140,
    groups: [{name: 'Yoga', uid: 'Yoga'}],
    birthdate: '2023-10-07',
    medical_checkups: '2023-10-07',
    role: 'S. Manager',
    team: 'Sales',
    status: 'Opłacone',
    paymentMethod: 'Przelew',
    age: '24',
    avatar: 'https://i.pravatar.cc/150?u=a092581d4ef9026700d',
    email: 'kristen.cooper@example.com',
  },
  {
    id: 6,
    name: 'Brian Kim',
    amountDue: 180,
    groups: [{name: 'Pilates', uid: 'Pilates'}],
    birthdate: '2023-10-06',
    medical_checkups: '2023-10-06',
    order: 'Rękawice bokserskie Eva Pro 14oz,\nSzczęka biała',
    role: 'P. Manager',
    team: 'Management',
    age: '29',
    avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026024d',
    email: 'brian.kim@example.com',
    status: 'Opłacone',
    paymentMethod: 'Przelew',
  },
  {
    id: 7,
    name: 'Michael Hunt',
    amountDue: 180,
    groups: [{name: 'Kickboxing Dinusie', uid: 'Kickboxing Dinusie'}],
    birthdate: '2023-10-02',
    medical_checkups: '2023-10-02',
    role: 'Designer',
    team: 'Design',
    status: 'Opłacone',
    paymentMethod: 'Gotówka',
    age: '27',
    avatar: 'https://i.pravatar.cc/150?u=a042581f4e29027007d',
    email: 'michael.hunt@example.com',
  },
  {
    id: 8,
    name: 'Samantha Brooks',
    amountDue: 110,
    groups: [{name: 'Kickboxing Juniorzy', uid: 'Kickboxing Juniorzy'}],
    birthdate: '2023-10-01',
    medical_checkups: '2023-10-01',
    role: 'HR Manager',
    team: 'HR',
    status: 'Opłacone',
    paymentMethod: 'Gotówka',
    age: '31',
    avatar: 'https://i.pravatar.cc/150?u=a042581f4e27027008d',
    email: 'samantha.brooks@example.com',
  },
  {
    id: 9,
    name: 'Frank Harrison',
    amountDue: 110,
    groups: [{name: 'Kickboxing Seniorzy', uid: 'Kickboxing Seniorzy'}],
    birthdate: '2023-10-01',
    medical_checkups: '2023-10-01',
    role: 'F. Manager',
    team: 'Finance',
    status: 'Nieopłacone',
    age: '33',
    avatar: 'https://i.pravatar.cc/150?img=4',
    email: 'frank.harrison@example.com',
  },
  {
    id: 10,
    name: 'Emma Adams',
    amountDue: 110,
    groups: [{name: 'Kickboxing Kadeci', uid: 'Kickboxing Kadeci'}],
    birthdate: '2023-10-01',
    medical_checkups: '2023-10-01',
    role: 'Ops Manager',
    team: 'Operations',
    status: 'Opłacone',
    paymentMethod: 'Gotówka',
    age: '35',
    avatar: 'https://i.pravatar.cc/150?img=5',
    email: 'emma.adams@example.com',
  },
  {
    id: 11,
    name: 'Brandon Stevens',
    amountDue: 140,
    groups: [{name: 'Kickboxing Kadeci', uid: 'Kickboxing Kadeci'}],
    birthdate: '2023-10-01',
    medical_checkups: '2023-10-01',
    role: 'Jr. Dev',
    team: 'Development',
    status: 'Opłacone',
    paymentMethod: 'Gotówka',
    age: '22',
    avatar: 'https://i.pravatar.cc/150?img=8',
    email: 'brandon.stevens@example.com',
  },
  {
    id: 12,
    name: 'Megan Richards',
    amountDue: 140,
    groups: [{name: 'Kickboxing Kadeci', uid: 'Kickboxing Kadeci'}],
    birthdate: '2023-09-26',
    medical_checkups: '2023-09-26',
    role: 'P. Manager',
    team: 'Product',
    status: 'Opłacone',
    paymentMethod: 'Gotówka',
    age: '28',
    avatar: 'https://i.pravatar.cc/150?img=10',
    email: 'megan.richards@example.com',
  },
  {
    id: 13,
    name: 'Oliver Scott',
    amountDue: 140,
    groups: [{name: 'Kickboxing Kadeci', uid: 'Kickboxing Kadeci'}],
    birthdate: '2023-09-26',
    medical_checkups: '2023-09-26',
    role: 'S. Manager',
    team: 'Security',
    status: 'Opłacone',
    paymentMethod: 'Gotówka',
    age: '37',
    avatar: 'https://i.pravatar.cc/150?img=12',
    email: 'oliver.scott@example.com',
  },
  {
    id: 14,
    name: 'Grace Allen',
    amountDue: 140,
    groups: [{name: 'Yoga', uid: 'Yoga'}],
    birthdate: '2023-09-26',
    medical_checkups: '2023-09-26',
    role: 'M. Specialist',
    team: 'Marketing',
    status: 'Opłacone',
    paymentMethod: 'Gotówka',
    age: '30',
    avatar: 'https://i.pravatar.cc/150?img=16',
    email: 'grace.allen@example.com',
  },
  {
    id: 15,
    name: 'Noah Carter',
    amountDue: 140,
    groups: [{name: 'Pilates', uid: 'Pilates'}],
    birthdate: '2023-09-26',
    medical_checkups: '2023-09-26',
    role: 'IT Specialist',
    team: 'I. Technology',
    status: 'Opłacone',
    paymentMethod: 'Gotówka',
    age: '31',
    avatar: 'https://i.pravatar.cc/150?img=15',
    email: 'noah.carter@example.com',
  },
  {
    id: 16,
    name: 'Ava Perez',
    amountDue: 180,
    groups: [
      {name: 'Kickboxing Seniorzy', uid: 'Kickboxing Seniorzy'},
      {name: 'Kickboxing Kadeci', uid: 'Kickboxing Kadeci'},
    ],
    birthdate: '2023-09-26',
    medical_checkups: '2023-09-26',
    role: 'Manager',
    team: 'Sales',
    status: 'Opłacone',
    paymentMethod: 'Gotówka',
    age: '29',
    avatar: 'https://i.pravatar.cc/150?img=20',
    email: 'ava.perez@example.com',
  },
  {
    id: 17,
    name: 'Liam Johnson',
    amountDue: 180,
    groups: [{name: 'Kickboxing Seniorzy', uid: 'Kickboxing Seniorzy'}],
    birthdate: '2023-09-26',
    medical_checkups: '2023-09-26',
    role: 'Data Analyst',
    team: 'Analysis',
    status: 'Opłacone',
    paymentMethod: 'Gotówka',
    age: '28',
    avatar: 'https://i.pravatar.cc/150?img=33',
    email: 'liam.johnson@example.com',
  },
  {
    id: 18,
    name: 'Sophia Taylor',
    amountDue: 180,
    groups: [
      {name: 'Kickboxing Seniorzy', uid: 'Kickboxing Seniorzy'},
      {name: 'Kickboxing Kadeci', uid: 'Kickboxing Kadeci'},
    ],
    birthdate: '2023-09-26',
    medical_checkups: '2023-09-26',
    role: 'QA Analyst',
    team: 'Testing',
    status: 'Opłacone',
    paymentMethod: 'Gotówka',
    age: '27',
    avatar: 'https://i.pravatar.cc/150?img=29',
    email: 'sophia.taylor@example.com',
  },
  {
    id: 19,
    name: 'Lucas Harris',
    amountDue: 140,
    groups: [
      {name: 'Kickboxing Seniorzy', uid: 'Kickboxing Seniorzy'},
      {name: 'Kickboxing Kadeci', uid: 'Kickboxing Kadeci'},
    ],
    birthdate: '2023-09-26',
    medical_checkups: '2023-09-26',
    role: 'Administrator',
    team: 'Information Technology',
    status: 'Opłacone',
    paymentMethod: 'Przelew',
    age: '32',
    avatar: 'https://i.pravatar.cc/150?img=50',
    email: 'lucas.harris@example.com',
  },
  {
    id: 20,
    name: 'Mia Robinson',
    amountDue: 140,
    groups: [
      {name: 'Kickboxing Seniorzy', uid: 'Kickboxing Seniorzy'},
      {name: 'Kickboxing Kadeci', uid: 'Kickboxing Kadeci'},
    ],
    birthdate: '2023-09-26',
    medical_checkups: '2023-09-26',
    role: 'Coordinator',
    team: 'Operations',
    status: 'Nieopłacone',
    age: '26',
    avatar: 'https://i.pravatar.cc/150?img=45',
    email: 'mia.robinson@example.com',
  },
];

export {columns, groupsOptions, statusOptions, users};
